# Generated by Django 5.1.5 on 2025-04-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='poke_coins',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
