# Generated by Django 5.2a1 on 2025-04-11 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='nickname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
