# Generated by Django 5.2a1 on 2025-04-25 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pokemon_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemon'},
        ),
    ]
