# Generated by Django 5.1.5 on 2025-04-26 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pokemon_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemon'},
        ),
    ]
